image: python:3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - pylint **/*.py

unit:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - coverage run --omit=.tests/*,*/__init__.py --source='./air_sdk' `which pytest` tests/*
  after_script:
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 hour

pages:
  stage: deploy
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  script:
    - cd docs; hugo --baseUrl $CI_PAGES_URL
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - master
