image: python:3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

static:
  stage: test
  before_script:
    - pip install semgrep
  script: semgrep --error --config=p/r2c-ci .
  only:
    changes:
      - "**/*.py"
  except:
    - tags

lint:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - pylint **/*.py
  except:
    - tags

unit:
  stage: test
  before_script:
    - pip install -r requirements-dev.txt
  script:
    - coverage run --omit=.tests/*,*/__init__.py --source='./air_sdk' `which pytest` tests/*
  after_script:
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 hour
  except:
    - tags

pages:
  stage: deploy
  image:
    name: urm.nvidia.com/docker-remote/klakegg/hugo:0.82.1-ext-alpine
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd docs; hugo --baseUrl $CI_PAGES_URL
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - main
  except:
    - tags

deploy:
  stage: deploy
  script:
    - mkdir /root/.ssh
    - echo $AIR_ADMIN_KEY | base64 -d > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - ssh-keyscan $AIR_MANAGER >> /root/.ssh/known_hosts
    - PKG_FILE=cumulus-air-sdk-${CI_COMMIT_TAG}.tar.gz
    - tar czf ${PKG_FILE} *
    - scp ${PKG_FILE} air-admin@${AIR_MANAGER}:/var/lib/pypi/packages/cumulus-air-sdk/${PKG_FILE}
  only:
    - tags
