image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

static:
  stage: test
  before_script:
    - pip install semgrep
  script: semgrep --error --config=p/r2c-ci .
  only:
    changes:
      - "**/*.py"
  except:
    - tags

lint:
  stage: test
  before_script:
    - pip install .[dev]
  script:
    - pylint **/*.py
  except:
    - tags

unit:
  stage: test
  before_script:
    - pip install .[dev]
  script: |
    coverage run --omit=.tests/*,*/__init__.py --source='./air_sdk' `which pytest` tests/*
    coverage report -m | tee /tmp/coverage
    coverage=$(cat /tmp/coverage | grep -i total | tr -s ' ' | cut -d ' ' -f 4 | cut -d '%' -f 1)
    if (( $coverage < 80 )); then echo 'ERROR: Coverage below accepted threshold!'; exit 1; fi
  after_script:
    - coverage html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - htmlcov/
    expire_in: 1 hour
  except:
    - tags
