repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.3 # Ruff version
    hooks:
      # Run the linter, and fix issues that are safely-fixable.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy air_sdk/v2 --config-file mypy.ini
        language: system
        types: [ python ]
        pass_filenames: false
