apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    nvidia.com/node_type: builder
  containers:
    - name: jnlp
      image: urm.nvidia.com/sw-switch-devops-docker/ml-jnlp:1.0.0
      workingDir: /tmp
      securityContext:
        runAsUser: 7331
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "2Gi"
          cpu: "2"

    - name: dind
      image: urm.nvidia.com/sw-switch-devops-docker/blossom_dind_gen:1.0.0
      imagePullPolicy: Always
      workingDir: /tmp
      securityContext:
        runAsUser: 7331
      resources:
        requests:
          memory: "6Gi"
          cpu: "16"
        limits:
          memory: "8Gi"
          cpu: "20"
      tty: true
      command: ['cat']
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker-daemon
      image: urm.nvidia.com/sw-switch-devops-docker/blossom_dind_gen:1.0.0
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""

  volumes:
    - name: nbu-sws
      persistentVolumeClaim:
        claimName: nbu-sws-pvc
        readOnly: false