apiVersion: v1
kind: Pod
spec:
  containers:
    - name: jnlp
      image: urm.nvidia.com/sw-switch-devops-docker/ml-jnlp:1.0.0
    - name: jf
      image: urm.nvidia.com/sw-switch-devops-docker/jfrog-cli:0.0.1
      volumeMounts:
        - mountPath: /nbu-sws
          name: nbu-sws
          mountPropagation: HostToContainer
          readOnly: false
      resources:
        requests:
          memory: "6Gi"
          cpu: "4"
        limits:
          memory: "8Gi"
          cpu: "6"
      command: [ 'cat' ]
      tty: true

  volumes:
    - name: nbu-sws
      persistentVolumeClaim:
        claimName: nbu-sws-pvc
        readOnly: false
